---
- name: Add Elastic gpg key
  rpm_key:
    key: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present
  tags:
    - rpm_key

- name: Add Elastic YUM repository
  yum_repository:
    baseurl: "https://artifacts.elastic.co/packages/{{ elasticrepo_version }}/yum"
    description: Elastic {{ elasticrepo_version }} packages
    name: elastic-{{ elasticrepo_version }}
    enabled: true
    gpgcheck: true
    gpgkey: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present
  tags:
    - yum_repository
